## bounty_manager.gd - Simple bounty system using QuestManager for tracking
## Bounties are quests generated by NPCs that the player can accept for gold rewards
extends Node

# =============================================================================
# SIGNALS
# =============================================================================

signal bounty_offered(bounty: Bounty)
signal bounty_accepted(bounty: Bounty)
signal bounty_completed(bounty: Bounty)
signal bounty_turned_in(bounty: Bounty)

# =============================================================================
# BOUNTY CLASS
# =============================================================================

class Bounty:
	var id: String
	var quest_id: String  # Links to QuestManager quest
	var giver_npc_id: String
	var giver_npc_name: String
	var giver_settlement: String
	var target_creature: String
	var target_count: int
	var region: String
	var direction_hint: String
	var reward_gold: int
	var reward_xp: int
	var is_accepted: bool = false
	var is_ready_for_turnin: bool = false
	var is_turned_in: bool = false

	func to_dict() -> Dictionary:
		return {
			"id": id,
			"quest_id": quest_id,
			"giver_npc_id": giver_npc_id,
			"giver_npc_name": giver_npc_name,
			"giver_settlement": giver_settlement,
			"target_creature": target_creature,
			"target_count": target_count,
			"region": region,
			"direction_hint": direction_hint,
			"reward_gold": reward_gold,
			"reward_xp": reward_xp,
			"is_accepted": is_accepted,
			"is_ready_for_turnin": is_ready_for_turnin,
			"is_turned_in": is_turned_in
		}

	static func from_dict(data: Dictionary) -> Bounty:
		var bounty := Bounty.new()
		bounty.id = data.get("id", "")
		bounty.quest_id = data.get("quest_id", "")
		bounty.giver_npc_id = data.get("giver_npc_id", "")
		bounty.giver_npc_name = data.get("giver_npc_name", "")
		bounty.giver_settlement = data.get("giver_settlement", "")
		bounty.target_creature = data.get("target_creature", "")
		bounty.target_count = data.get("target_count", 3)
		bounty.region = data.get("region", "")
		bounty.direction_hint = data.get("direction_hint", "")
		bounty.reward_gold = data.get("reward_gold", 100)
		bounty.reward_xp = data.get("reward_xp", 50)
		bounty.is_accepted = data.get("is_accepted", false)
		bounty.is_ready_for_turnin = data.get("is_ready_for_turnin", false)
		bounty.is_turned_in = data.get("is_turned_in", false)
		return bounty

# =============================================================================
# STATE
# =============================================================================

## All bounties (active, pending, completed)
var bounties: Dictionary = {}  # bounty_id -> Bounty

## NPC's current offered bounty (one per NPC)
var npc_offered_bounties: Dictionary = {}  # npc_id -> bounty_id

## Completed bounty IDs (to prevent re-offering)
var completed_bounty_ids: Array[String] = []

## Bounty ID counter
var _bounty_counter: int = 0

## Current settlement context (set when entering a settlement)
var current_settlement: String = "village_elder_moor"

# =============================================================================
# LIFECYCLE
# =============================================================================

func _ready() -> void:
	# Connect to QuestManager signals for tracking
	if QuestManager:
		QuestManager.quest_updated.connect(_on_quest_updated)
		QuestManager.objective_completed.connect(_on_objective_completed)

# =============================================================================
# BOUNTY GENERATION
# =============================================================================

## Generate a bounty for an NPC based on current location
func generate_bounty_for_npc(npc_id: String, npc_name: String) -> Bounty:
	# Check if NPC already has an offered bounty
	if npc_offered_bounties.has(npc_id):
		var existing_id: String = npc_offered_bounties[npc_id]
		if bounties.has(existing_id):
			var existing: Bounty = bounties[existing_id]
			if not existing.is_accepted and not existing.is_turned_in:
				return existing

	# Get a random nearby region for variety in bounties
	var region: String = WorldLexicon.get_random_nearby_region(current_settlement)

	# Get random creature for this region
	var creature: String = WorldLexicon.get_random_creature_for_region(region)
	var creature_tier: int = WorldLexicon.get_creature_tier(creature)

	# Calculate target count and rewards based on tier
	var target_count: int
	var base_gold: int
	var base_xp: int

	match creature_tier:
		1:  # Easy creatures
			target_count = randi_range(3, 5)
			base_gold = randi_range(50, 100)
			base_xp = randi_range(25, 50)
		2:  # Medium creatures
			target_count = randi_range(2, 4)
			base_gold = randi_range(100, 175)
			base_xp = randi_range(50, 100)
		3:  # Hard creatures
			target_count = randi_range(2, 3)
			base_gold = randi_range(175, 275)
			base_xp = randi_range(100, 175)
		_:  # Very hard creatures (tier 4+)
			target_count = randi_range(1, 2)
			base_gold = randi_range(275, 400)
			base_xp = randi_range(175, 250)

	# Create bounty
	_bounty_counter += 1
	var bounty := Bounty.new()
	bounty.id = "bounty_%d_%d" % [Time.get_ticks_msec(), _bounty_counter]
	bounty.quest_id = "quest_" + bounty.id
	bounty.giver_npc_id = npc_id
	bounty.giver_npc_name = npc_name
	bounty.giver_settlement = current_settlement
	bounty.target_creature = creature
	bounty.target_count = target_count
	bounty.region = region
	bounty.direction_hint = WorldLexicon.get_random_direction(region)
	bounty.reward_gold = base_gold
	bounty.reward_xp = base_xp

	# Store bounty
	bounties[bounty.id] = bounty
	npc_offered_bounties[npc_id] = bounty.id

	bounty_offered.emit(bounty)
	return bounty


## Get the dialogue text for offering a bounty
func get_bounty_offer_text(bounty: Bounty) -> String:
	var creature_name: String = WorldLexicon.get_creature_display(bounty.target_creature)

	# Build a clear, actionable bounty description
	var text := "I've heard tell of %s causing trouble. %s. " % [creature_name.to_lower(), bounty.direction_hint]
	text += "Kill %d of them and I'll pay you %d gold for your trouble." % [bounty.target_count, bounty.reward_gold]

	return text


## Get short bounty description for journal
func get_bounty_description(bounty: Bounty) -> String:
	var creature_name: String = WorldLexicon.get_creature_display(bounty.target_creature)
	var singular: String = WorldLexicon.get_creature_display(bounty.target_creature, false)

	return "Kill %d %s %s. Return to %s in %s for %d gold." % [
		bounty.target_count,
		creature_name.to_lower() if bounty.target_count > 1 else singular,
		bounty.direction_hint,
		bounty.giver_npc_name,
		WorldLexicon.get_region_name(bounty.giver_settlement),
		bounty.reward_gold
	]

# =============================================================================
# BOUNTY ACCEPTANCE
# =============================================================================

## Accept a bounty and create the quest
func accept_bounty(bounty_id: String) -> bool:
	if not bounties.has(bounty_id):
		push_warning("[BountyManager] Bounty not found: %s" % bounty_id)
		return false

	var bounty: Bounty = bounties[bounty_id]
	if bounty.is_accepted:
		return false  # Already accepted

	# Create quest data for QuestManager
	# Extract region from settlement (e.g., "village_elder_moor" -> "elder_moor")
	var turn_in_region: String = bounty.giver_settlement
	if turn_in_region.begins_with("village_"):
		turn_in_region = turn_in_region.substr(8)  # Remove "village_" prefix
	elif turn_in_region.begins_with("city_"):
		turn_in_region = turn_in_region.substr(5)  # Remove "city_" prefix
	elif turn_in_region.begins_with("town_"):
		turn_in_region = turn_in_region.substr(5)  # Remove "town_" prefix

	var quest_data := {
		"id": bounty.quest_id,
		"title": "Bounty: Hunt %s" % WorldLexicon.get_creature_display(bounty.target_creature),
		"description": get_bounty_description(bounty),
		"is_main_quest": false,
		# Quest source and giver tracking
		"quest_source": "npc_bounty",
		"giver_npc_id": bounty.giver_npc_id,
		"giver_npc_type": "guard",
		"giver_region": turn_in_region,
		# Turn-in configuration: Any guard in the same region can accept
		"turn_in_type": "npc_type_in_region",
		"turn_in_target": "guard",
		"turn_in_region": turn_in_region,
		"turn_in_zone": turn_in_region,
		"objectives": [
			{
				"id": "kill_targets",
				"description": "Kill %d %s" % [bounty.target_count, WorldLexicon.get_creature_display(bounty.target_creature).to_lower()],
				"type": "kill",
				"target": bounty.target_creature,
				"required_count": bounty.target_count
			}
		],
		"rewards": {
			"gold": bounty.reward_gold,
			"xp": bounty.reward_xp
		}
	}

	# Register quest with QuestManager
	_register_bounty_quest(quest_data)

	# Debug logging for quest turn-in configuration
	print("[BountyManager] Quest created: turn_in_type=%s, turn_in_target=%s, turn_in_region=%s" % [
		quest_data.get("turn_in_type", "unknown"),
		quest_data.get("turn_in_target", "unknown"),
		quest_data.get("turn_in_region", "unknown")
	])

	# Start the quest
	if QuestManager.start_quest(bounty.quest_id):
		bounty.is_accepted = true
		bounty_accepted.emit(bounty)

		# Force track the bounty quest so compass shows it
		QuestManager.set_tracked_quest(bounty.quest_id)

		# Show notification
		var hud := get_tree().get_first_node_in_group("hud")
		if hud and hud.has_method("show_notification"):
			hud.show_notification("Bounty Accepted: Hunt %s" % WorldLexicon.get_creature_display(bounty.target_creature))

		return true

	return false


## Register bounty quest data with QuestManager's database
func _register_bounty_quest(quest_data: Dictionary) -> void:
	# Parse the quest and add to quest_database
	var quest := QuestManager.Quest.new()
	quest.id = quest_data.get("id", "")
	quest.title = quest_data.get("title", "Unknown Quest")
	quest.description = quest_data.get("description", "")
	quest.is_main_quest = quest_data.get("is_main_quest", false)
	quest.rewards = quest_data.get("rewards", {})
	quest.giver_npc_id = quest_data.get("giver_npc_id", "")  # Track quest giver for turn-in
	quest.giver_npc_type = quest_data.get("giver_npc_type", "guard")  # Bounties are given by guards
	quest.giver_region = quest_data.get("giver_region", "")  # Region for turn-in to any guard in region

	for obj_data: Variant in quest_data.get("objectives", []):
		if obj_data is Dictionary:
			var obj := QuestManager.Objective.new()
			obj.id = obj_data.get("id", "")
			obj.description = obj_data.get("description", "")
			obj.type = obj_data.get("type", "")
			obj.target = obj_data.get("target", "")
			obj.required_count = obj_data.get("required_count", 1)
			obj.is_optional = obj_data.get("is_optional", false)
			quest.objectives.append(obj)

	QuestManager.quest_database[quest.id] = quest

# =============================================================================
# BOUNTY TRACKING
# =============================================================================

## Called when quest progress updates
func _on_quest_updated(quest_id: String, _objective_id: String) -> void:
	# Check if this is a bounty quest
	var bounty: Bounty = _get_bounty_by_quest_id(quest_id)
	if not bounty:
		return

	# Check if kill objective is complete
	if QuestManager.is_quest_active(quest_id):
		var quest: QuestManager.Quest = QuestManager.get_quest(quest_id)
		if quest:
			for obj: QuestManager.Objective in quest.objectives:
				if obj.id == "kill_targets" and obj.is_completed:
					bounty.is_ready_for_turnin = true
					bounty_completed.emit(bounty)

					var hud := get_tree().get_first_node_in_group("hud")
					if hud and hud.has_method("show_notification"):
						hud.show_notification("Bounty Ready: Return to %s" % bounty.giver_npc_name)
					break


## Called when an objective completes
func _on_objective_completed(quest_id: String, objective_id: String) -> void:
	var bounty: Bounty = _get_bounty_by_quest_id(quest_id)
	if not bounty:
		return

	if objective_id == "kill_targets":
		bounty.is_ready_for_turnin = true
		bounty_completed.emit(bounty)


## Get bounty by quest ID
func _get_bounty_by_quest_id(quest_id: String) -> Bounty:
	for bounty_id: String in bounties:
		var bounty: Bounty = bounties[bounty_id]
		if bounty.quest_id == quest_id:
			return bounty
	return null

# =============================================================================
# BOUNTY TURN-IN
# =============================================================================

## Check if player can turn in a bounty to this NPC
func can_turn_in_bounty(npc_id: String) -> bool:
	for bounty_id: String in bounties:
		var bounty: Bounty = bounties[bounty_id]
		if bounty.giver_npc_id == npc_id and bounty.is_accepted and bounty.is_ready_for_turnin and not bounty.is_turned_in:
			return true
	return false


## Get the bounty that can be turned in to this NPC
func get_turnin_bounty(npc_id: String) -> Bounty:
	for bounty_id: String in bounties:
		var bounty: Bounty = bounties[bounty_id]
		if bounty.giver_npc_id == npc_id and bounty.is_accepted and bounty.is_ready_for_turnin and not bounty.is_turned_in:
			return bounty
	return null


## Turn in a completed bounty
func turn_in_bounty(bounty_id: String) -> bool:
	if not bounties.has(bounty_id):
		return false

	var bounty: Bounty = bounties[bounty_id]
	if not bounty.is_ready_for_turnin or bounty.is_turned_in:
		return false

	# Complete the quest (awards rewards via QuestManager)
	QuestManager.complete_quest(bounty.quest_id)

	# Mark bounty as turned in
	bounty.is_turned_in = true
	completed_bounty_ids.append(bounty_id)

	# Clear NPC's offered bounty so they can offer a new one
	if npc_offered_bounties.get(bounty.giver_npc_id) == bounty_id:
		npc_offered_bounties.erase(bounty.giver_npc_id)

	bounty_turned_in.emit(bounty)

	# Show notification
	var hud := get_tree().get_first_node_in_group("hud")
	if hud and hud.has_method("show_notification"):
		hud.show_notification("Bounty Complete! +%d Gold, +%d XP" % [bounty.reward_gold, bounty.reward_xp])

	return true


## Get turn-in dialogue text
func get_turnin_text(_bounty: Bounty) -> String:
	return WorldLexicon.get_bounty_template("completion")

# =============================================================================
# ACCESSORS
# =============================================================================

## Check if NPC has a bounty to offer (that player hasn't already accepted)
func has_bounty_available(npc_id: String) -> bool:
	# Check if NPC has a pending offer
	if npc_offered_bounties.has(npc_id):
		var bounty_id: String = npc_offered_bounties[npc_id]
		if bounties.has(bounty_id):
			var bounty: Bounty = bounties[bounty_id]
			# Available if not accepted and not turned in
			return not bounty.is_accepted and not bounty.is_turned_in

	# NPC can offer a new bounty
	return true


## Get all active (accepted but not turned in) bounties
func get_active_bounties() -> Array[Bounty]:
	var active: Array[Bounty] = []
	for bounty_id: String in bounties:
		var bounty: Bounty = bounties[bounty_id]
		if bounty.is_accepted and not bounty.is_turned_in:
			active.append(bounty)
	return active


## Set current settlement (called when player enters a settlement)
func set_current_settlement(settlement_id: String) -> void:
	current_settlement = settlement_id

# =============================================================================
# SAVE/LOAD
# =============================================================================

func to_dict() -> Dictionary:
	var bounties_data: Dictionary = {}
	for bounty_id: String in bounties:
		bounties_data[bounty_id] = bounties[bounty_id].to_dict()

	return {
		"bounties": bounties_data,
		"npc_offered_bounties": npc_offered_bounties.duplicate(),
		"completed_bounty_ids": completed_bounty_ids.duplicate(),
		"bounty_counter": _bounty_counter,
		"current_settlement": current_settlement
	}


func from_dict(data: Dictionary) -> void:
	bounties.clear()
	npc_offered_bounties.clear()
	completed_bounty_ids.clear()

	var bounties_data: Dictionary = data.get("bounties", {})
	for bounty_id: String in bounties_data:
		var bounty := Bounty.from_dict(bounties_data[bounty_id])
		bounties[bounty_id] = bounty

	npc_offered_bounties = data.get("npc_offered_bounties", {}).duplicate()

	var completed: Array = data.get("completed_bounty_ids", [])
	for c: Variant in completed:
		completed_bounty_ids.append(str(c))

	_bounty_counter = data.get("bounty_counter", 0)
	current_settlement = data.get("current_settlement", "elder_moor")


func reset_for_new_game() -> void:
	bounties.clear()
	npc_offered_bounties.clear()
	completed_bounty_ids.clear()
	_bounty_counter = 0
	current_settlement = "elder_moor"
